import os
from PIL import Image
from google import genai
from google.genai import types
from app.core.config import GEMINI_API_KEY
from app.services.prompt import get_image_generation_config

client = genai.Client(api_key=GEMINI_API_KEY)


def analyze_and_generate_views(image_path: str, product_name: str, upload_dir: str):
    img = Image.open(image_path)

    model_id = "gemini-2.5-flash-image" 

    prompt, angles = get_image_generation_config(product_name)

    # Keep regenerating until we get exactly 4 images
    while True:
        response = client.models.generate_content(
            model=model_id,
            contents=[prompt, img],
            config=types.GenerateContentConfig(
                response_modalities=["TEXT", "IMAGE"], 
                candidate_count=1
            )
        )

        views = {}
        image_count = 0

        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    if image_count < 4:
                        angle = angles[image_count]
                        filename = f"nano_{angle}_{os.path.basename(image_path)}"
                        save_path = os.path.join(upload_dir, filename)
                        
                        with open(save_path, "wb") as f:
                            f.write(part.inline_data.data)
                        
                        views[angle] = filename
                        image_count += 1
        
        # If we got exactly 4 images, break the loop and return
        if image_count == 4:
            break
    
    return {
        "views": views,
        "analysis": {"status": "Generated by Gemini Image"}
    }