# from google import genai
# from google.genai import types
# from PIL import Image
# import os
# from app.core.config import GEMINI_API_KEY

# client = genai.Client(api_key=GEMINI_API_KEY)


# def analyze_and_generate_views(image_path: str, product_name: str, upload_dir: str):
#     # 1. Load the original image you sent from the frontend
#     img = Image.open(image_path)

#     # 2. Call the image-to-image capable model
#     model_id = "gemini-2.5-flash-image" 

#     prompt = f"""
#     Reference Product: {product_name}
#     Action: Using the provided image, generate 4 new high-quality images.
#     Angles: 1. Front View, 2. Back View, 3. Left Side, 4. Right Side.
#     Requirements: Maintain 100% color and texture consistency. Use a flat 2D style.
#     Output: Return 4 image parts.
#     """

#     # 3. CRITICAL: Set response_modalities to ["IMAGE"]
#     response = client.models.generate_content(
#         model=model_id,
#         contents=[prompt, img],
#         config=types.GenerateContentConfig(
#             response_modalities=["IMAGE"]
#         )
#     )

#     views = {}
#     angles = ["front", "back", "left", "right"]
#     image_count = 0

#     # 4. Catch the images coming back from Nano Banana
#     for part in response.candidates[0].content.parts:
#         if part.inline_data and image_count < 4:
#             angle = angles[image_count]
#             filename = f"nano_{angle}_{os.path.basename(image_path)}"
#             save_path = os.path.join(upload_dir, filename)
            
#             # Save the raw bytes directly to your project's upload folder
#             with open(save_path, "wb") as f:
#                 f.write(part.inline_data.data)
            
#             views[angle] = filename
#             image_count += 1

#     return {
#         "views": views,
#         "analysis": {"status": "Generated by Nano Banana"}
#     }



from openai import OpenAI
import os
import requests
from app.core.config import OPENAI_API_KEY

client = OpenAI(api_key=OPENAI_API_KEY)


def analyze_and_generate_views(image_path: str, product_name: str, upload_dir: str):
    os.makedirs(upload_dir, exist_ok=True)

    base_prompt = f"""
    Reference Product: {product_name}

    Rules:
    - Maintain same color and texture
    - Flat 2D e-commerce style
    - Same lighting and proportions
    - Clean white background
    """

    angles = ["front", "back", "left", "right"]
    views = {}

    for angle in angles:
        prompt = f"Reference Product: {product_name} Rules: - Maintain same color and texture - Flat 2D e-commerce style - Same lighting and proportions - Clean white background, Generate ONLY the 'front', 'back', 'left', 'right' view."

        with open(image_path, "rb") as image_file:
            result = client.images.edit(
                model="dall-e-2",
                image=image_file,
                prompt=prompt,
                size="1024x1024"
            )

        image_url = result.data[0].url  # ✅ DALL·E 2 returns URL
        response = requests.get(image_url)

        filename = f"openai_{angle}_{os.path.basename(image_path)}"
        save_path = os.path.join(upload_dir, filename)

        with open(save_path, "wb") as f:
            f.write(response.content)

        views[angle] = filename

    return {
        "views": views,
        "analysis": {
            "status": "Generated by DALL·E 2"
        }
    }
